Cucumber 3 changes
mikhaillopandia/howitzer_cucumber_freelancer pull request #3
Opened 2017-11-22 22:11 UTC by mikhaillopandia

Changes have been applied according to https://cucumber.io/blog/2017/09/21/upgrading-to-cucumber-3

2017-11-24 09:58 UTC, Lec1k commented on features/support/transformers.rb
> +  transformer: lambda do |page|
For one line transformers it's better to use functional style:
```
 transformer: -> (page) { page }
```

2017-11-24 09:58 UTC, Lec1k commented on features/support/transformers.rb
> +  transformer: lambda do |menu_intem|
same here

2017-11-24 09:58 UTC, Lec1k commented on features/support/transformers.rb
> +  transformer: lambda do |email|
same

2017-11-24 09:58 UTC, Lec1k commented on features/support/transformers.rb
> +  transformer: lambda do |email|
same

2017-11-24 14:54 UTC, alexey-voronenko requested changes
See comments above

2017-11-24 19:09 UTC, mikhaillopandia commented
@Lec1k thank you a lot for review, changes have been applied, check now, please.

2017-11-25 17:43 UTC, romikoops approved these changes

2017-11-25 18:00 UTC, merged